version: '3'

services:
  flask-app:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@p${POSTGRES_HOST}:5432/${POSTGRES_DB}

  react-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
