version: '3'

services:
  flask-app:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@p${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - TZ=America/New_York

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"                     
    environment:
      - REACT_APP_API_URL=http://flask-app:5000  
    depends_on:
      - flask-app

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - TZ=America/New_York
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
