
export const jobTitles = [
    'SWE',
    'SDE',
    'Full Stack',
    'Frontend',
    'Backend',
    'Cloud',
    'Data Engineering',
    'DevOps Engineer',
    'Automation',
    'Mobile App Developer',
    'Database Administrator',
    'ML Ops',
    'AI Engineer',
    'ML Engineer',
  ];

export const platformTypes = [
    'Company Website',
    'LinkedIn',
    'Indeed',
    'Built-In',
    'HandShake',
    'Monster',
    'CareerBuilder',
    'SimplyHired',
    'Dice',
    'ZipRecruiter',
    'Twitter',
    'Other'
  ];

export const applicationStatusOptions = [
  'Applied',
  'OA Received',
  'Tech Interview',
  'Rejected',
  'Accepted'
]

export const usStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming"
];
